### ISSUE TITLE
Hamburger component missing display none on desktop sizes

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#185]
https://github.com/infinum/eightshift-frontend-libs/blob/1d2c31006701cbbe38e0a83c969c3bb597cc1889/blocks/init/src/Blocks/components/hamburger/hamburger-style.scss#L14-L23

a 

```scss
@include media(desktop up) {
	display: none;
}
```

is missing in the styling (hamburger is shown on the desktop size).
